//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotaFiscal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NotaFiscal.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use mobile data network.
        /// </summary>
        public static string ConfigurationPage3g {
            get {
                return ResourceManager.GetString("ConfigurationPage3g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show confirmation 
        ///and conclusion pages.
        /// </summary>
        public static string ConfigurationPageHide {
            get {
                return ResourceManager.GetString("ConfigurationPageHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Institution.
        /// </summary>
        public static string ConfigurationPageSelect {
            get {
                return ResourceManager.GetString("ConfigurationPageSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support: doenotafiscal@gmail.com.
        /// </summary>
        public static string ConfigurationPageSupport {
            get {
                return ResourceManager.GetString("ConfigurationPageSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: 1.0.0.0.
        /// </summary>
        public static string ConfigurationPageVersion {
            get {
                return ResourceManager.GetString("ConfigurationPageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 receipt has not been sent yet!.
        /// </summary>
        public static string HomePage1NotSent {
            get {
                return ResourceManager.GetString("HomePage1NotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, all receipts were successfully sent!.
        /// </summary>
        public static string HomePageAllSent {
            get {
                return ResourceManager.GetString("HomePageAllSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To select the institution you 
        ///want to make a donation 
        ///and some other stuff.
        /// </summary>
        public static string HomePageConfiguration {
            get {
                return ResourceManager.GetString("HomePageConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to take a picture, or 
        ///to select your receipt from the gallery.
        /// </summary>
        public static string HomePageNotinha {
            get {
                return ResourceManager.GetString("HomePageNotinha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  receipts have not been sent yet!.
        /// </summary>
        public static string HomePageNotSent {
            get {
                return ResourceManager.GetString("HomePageNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To know how you should take 
        ///the picture of your receipt.
        /// </summary>
        public static string HomePageQuestion {
            get {
                return ResourceManager.GetString("HomePageQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Institution.
        /// </summary>
        public static string InstitutionsPageRandom {
            get {
                return ResourceManager.GetString("InstitutionsPageRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, you just made 
        ///a donation to the institution:.
        /// </summary>
        public static string LastPageCongratulations {
            get {
                return ResourceManager.GetString("LastPageCongratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your support!.
        /// </summary>
        public static string LastPageThanks {
            get {
                return ResourceManager.GetString("LastPageThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string PhotoPageProcessing {
            get {
                return ResourceManager.GetString("PhotoPageProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing and Submitting....
        /// </summary>
        public static string PhotoPageProcessing2 {
            get {
                return ResourceManager.GetString("PhotoPageProcessing2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Try to follow these constraints while
        ///taking your picture..
        /// </summary>
        public static string QuestionPage1 {
            get {
                return ResourceManager.GetString("QuestionPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) If the receipt is too big, try bending
        ///the paper..
        /// </summary>
        public static string QuestionPage2 {
            get {
                return ResourceManager.GetString("QuestionPage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3) Avoid taking pictures if the receipt
        ///is unreadable or  more than 1 month old.
        ///Prefer dark backgrounds..
        /// </summary>
        public static string QuestionPage3 {
            get {
                return ResourceManager.GetString("QuestionPage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4) Also avoid taking crooked receipt 
        ///photos or hiding crucial information..
        /// </summary>
        public static string QuestionPage4 {
            get {
                return ResourceManager.GetString("QuestionPage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] questionspage1 {
            get {
                object obj = ResourceManager.GetObject("questionspage1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] questionspage2 {
            get {
                object obj = ResourceManager.GetObject("questionspage2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] questionspage3 {
            get {
                object obj = ResourceManager.GetObject("questionspage3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] questionspage4 {
            get {
                object obj = ResourceManager.GetObject("questionspage4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
